#!/usr/bin/env python3
"""Development-log helper for the Computational Finance projects.

Student commands (run from anywhere inside the repository):

    python tools/logtool.py init                  # once, after creating the repository
    python tools/logtool.py new "Short title"     # create a log entry (fills in date, author, code)
    python tools/logtool.py save [-m "message"]   # freeze figures, check, commit and push
    python tools/logtool.py check                 # check the format of all entries
    python tools/logtool.py experiment NAME       # new experiment folder from the template
    python tools/logtool.py figinfo ENTRY         # how the figures of an entry were produced
    python tools/logtool.py reproduce [--list]    # run the commands in REPRODUCE.md

Other commands:

    python tools/logtool.py index                 # rebuild log/README.md (automatic)
    python tools/logtool.py export [--ref p1] [--format pdf|html|md] [-o FILE]
    python tools/logtool.py stats  [--ref p1]     # regularity and authorship overview

Only the Python standard library is needed.  `export --format pdf` needs
pandoc and a LaTeX engine; `--format html` needs pandoc only.
"""

import argparse
import datetime as dt
import io
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
from collections import defaultdict
from pathlib import Path

ENTRY_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})_([a-z0-9][a-z0-9-]*)\.md$")
FIELD_RE = re.compile(r"^\s*[-*]\s*\*\*([^*]+?):\*\*\s*(.*?)\s*$")
REQUIRED_FIELDS = ["Date", "Author", "Code"]
REQUIRED_SECTIONS = ["Goal", "Method", "Code and runs", "Results", "Interpretation", "Next steps"]
OPTIONAL_SECTIONS = ["AI assistance", "Related entries"]
NO_CODE = {"n/a", "none", "-"}
IMG_RE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)")
LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)")
INDEX_START = "<!-- index:start (generated by tools/logtool.py index; do not edit below) -->"
INDEX_END = "<!-- index:end -->"


# ----------------------------------------------------------------- helpers
def repo_root() -> Path:
    """The repository containing the current directory, else the one containing this file."""
    for where in (Path.cwd(), Path(__file__).resolve().parent):
        r = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=where,
                           capture_output=True, text=True)
        if r.returncode == 0:
            return Path(r.stdout.strip())
    return Path(__file__).resolve().parent.parent


ROOT = repo_root()
LOG = ROOT / "log"


def git(*args, cwd=None, check=True) -> str:
    r = subprocess.run(["git", *args], cwd=cwd or ROOT, capture_output=True, text=True)
    if check and r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed:\n{r.stderr}")
    return r.stdout.strip()


def status_paths(*paths, root: Path = None) -> list:
    """Paths reported by `git status --porcelain` (new, changed, deleted, untracked)."""
    r = subprocess.run(["git", "status", "--porcelain", "--untracked-files=all", "--", *paths],
                       cwd=root or ROOT, capture_output=True, text=True)
    return [ln[3:].split(" -> ")[-1].strip('"') for ln in r.stdout.splitlines() if len(ln) > 3]


def load_project(root: Path = ROOT) -> dict:
    p = root / "project.json"
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    return {"members": []}


def member_names(project: dict) -> list:
    return [m["name"] for m in project.get("members", [])]


def slugify(text: str) -> str:
    s = text.lower()
    s = (s.replace("ą", "a").replace("ć", "c").replace("ę", "e").replace("ł", "l")
          .replace("ń", "n").replace("ó", "o").replace("ś", "s").replace("ź", "z").replace("ż", "z"))
    words = [w for w in re.split(r"[^a-z0-9]+", s) if w]
    out = ""
    for w in words:                       # whole words, at most about 50 characters
        if out and len(out) + 1 + len(w) > 50:
            break
        out = f"{out}-{w}" if out else w
    return out[:50] or "entry"


PROJECTS = {
    1: ("Machine-learning regression for American path-dependent contracts",
        "M. Gambara, G. Livieri, A. Pallavicini (2025). Machine-learning regression methods for "
        "American-style path-dependent contracts. Quantitative Finance 25(6), 895-918."),
    2: ("Reinforcement learning for trade execution",
        "P. Cheridito, M. Weiss (2026). Reinforcement learning for trade execution with market and "
        "limit orders. Quantitative Finance 26(6), 833-853."),
    3: ("Regression-based dual bounds for American options",
        "D. A. Cline (2026). Efficient upper bounds for American options: regression-based duals "
        "from backward primals. Quantitative Finance 26(7), 1071-1089."),
    4: ("Moving average options by GPR-GHQ",
        "L. Goudenege, A. Molent, A. Zanette (2022). Moving average options: Machine learning and "
        "Gauss-Hermite quadrature for a double non-Markovian problem. EJOR 303(2), 958-974."),
    5: ("Nonparametric estimation of expected shortfall",
        "D. Bartl, S. Eckstein (2026). Optimal nonparametric estimation of the expected shortfall "
        "risk. SIAM J. Financial Math. 17(3), 691-727."),
    6: ("Quant GANs for intraday data",
        "M. Wiese, R. Knobloch, R. Korn, P. Kretschmer (2020). Quant GANs: Deep generation of "
        "financial time series. Quantitative Finance 20(9), 1419-1440."),
    7: ("Diffusion models for rare-event dependence",
        "T. Takahashi, T. Mizuno (2025). Generation of synthetic financial time series by "
        "diffusion models. Quantitative Finance 25(10), 1507-1516."),
    8: ("Deep RL for market-maker inventory management",
        "O. F. Vicente, F. Fernandez, J. Garcia (2023). Automated market maker inventory "
        "management with deep reinforcement learning. Applied Intelligence 53, 22249-22266."),
    9: ("Deep kernel hedging with random features",
        "J.-L. Dupret, D. Hainaut, E. Motte (2026). Deep kernel hedging. "
        "arXiv:2609.34474."),
    10: ("Optimised multilevel Monte Carlo for nested simulation",
         "A. Boumezoued, A. Cherchali, V. Lemaire, G. Pages, M. Truc (2025). Optimized multi-level "
         "Monte Carlo parametrization and antithetic sampling for nested simulations. "
         "Methodol. Comput. Appl. Probab. 28(3)."),
}


def ask(question, default=""):
    """Prompt on the terminal; returns the default when not interactive."""
    if not sys.stdin.isatty():
        return default
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{question}{suffix}: ").strip()
    except EOFError:
        return default
    return ans or default


def yes(question, default=True, assume=False):
    if assume:
        return True
    ans = ask(question + (" (Y/n)" if default else " (y/N)"), "y" if default else "n")
    return ans.lower().startswith("y")


def tex_escape(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%")
             .replace("_", r"\_").replace("#", r"\#").replace("$", r"\$"))


class Entry:
    def __init__(self, path: Path):
        self.path = path
        self.name = path.name
        self.text = path.read_text(encoding="utf-8")
        m = ENTRY_RE.match(path.name)
        self.file_date = m.group(1) if m else None
        self.title = ""
        self.fields = {}
        self.items = {}           # sub-items of a field, e.g. the list under "Runs"
        self.sections = {}
        self._parse()

    def _parse(self):
        current = None
        in_code = False
        last_field = None
        for line in self.text.splitlines():
            if line.strip().startswith("```"):
                in_code = not in_code
            if not in_code and line.startswith("# ") and not self.title:
                self.title = line[2:].strip()
                continue
            if not in_code and line.startswith("## "):
                current = line[3:].strip()
                self.sections[current] = []
                continue
            if current is None:
                fm = FIELD_RE.match(line)
                sub = re.match(r"^\s{2,}[-*]\s+(.*\S)\s*$", line)
                if fm:
                    last_field = fm.group(1).strip()
                    self.fields[last_field] = fm.group(2).strip()
                    self.items[last_field] = []
                elif sub and last_field:
                    self.items[last_field].append(sub.group(1))
            else:
                self.sections[current].append(line)

    @property
    def date(self):
        return self.fields.get("Date") or self.file_date or ""

    @property
    def authors(self):
        a = self.fields.get("Author", "")
        return [x.strip() for x in re.split(r",|;| and ", a) if x.strip()]

    def section_text(self, name):
        body = "\n".join(self.sections.get(name, []))
        return re.sub(r"<!--.*?-->", "", body, flags=re.S).strip()


def added_times(ref: str = "HEAD") -> dict:
    """{entry file name: time (seconds) of the commit that added it}."""
    out, t = {}, None
    r = subprocess.run(["git", "log", ref, "--reverse", "--diff-filter=A", "--format=@%at",
                        "--name-only", "--", "log/"], cwd=ROOT, capture_output=True, text=True)
    for line in r.stdout.splitlines():
        if line.startswith("@"):
            t = int(line[1:])
        elif line.strip() and t is not None:
            out.setdefault(Path(line.strip()).name, t)
    return out


def entries(log_dir: Path = LOG, ref: str = "HEAD") -> list:
    """Entries in chronological order: by date, then by when they were first
    committed (entries not committed yet come last), then by name."""
    out = [Entry(p) for p in sorted(log_dir.glob("*.md"))
           if p.name.lower() != "readme.md" and not p.name.startswith("_")]
    added = added_times(ref) if (ROOT / ".git").exists() else {}
    return sorted(out, key=lambda e: (e.date, added.get(e.name, float("inf")), e.name))


# ----------------------------------------------------------------- new
TEMPLATE = """# {title}

- **Date:** {date}
- **Author:** {author}
- **Code:** {code}

## Goal
<!-- The question this entry tries to answer. One or two sentences. -->

## Method
<!-- What was implemented or tried, with enough detail to repeat it:
     model, parameters, number of paths, seeds, basis, etc.
     Maths: $inline$ and, on separate lines with blank lines around them,
     $$
     display
     $$ -->

## Code and runs
{code_note}

## Results
<!-- Numbers produced by code in this repository: a table, a figure or program
     output in a code block. Give Monte Carlo standard errors where relevant.
     Embed a figure with  ![caption](figs/lsm_basis-base.png)  (path relative to
     log/). `save` copies every embedded figure into this entry's own folder
     log/figs/<entry>/, so that later runs cannot change what this entry shows. -->

## Interpretation
<!-- What do the results mean? Were they expected? If not, why not? -->

## Next steps
<!-- What will be tried next, and why. -->

## AI assistance
<!-- Optional. If AI tools were used for this step: what for, how the
     output was checked, and what (if anything) was wrong with it.
     Delete this section if not applicable. -->
"""

CODE_NOTE = """<!-- Which scripts, configurations and parameters produced the results below,
     e.g. `python experiments/lsm_basis/run.py hard` with n_paths changed to 10^6.
     If the code differed from the commit above (uncommitted changes), say how.
     If anything was run outside this repository (Colab, a cluster), say where and
     from which commit, and where you put the results in the repository
     (experiments/<name>/imported/...). -->"""

CODE_EXT = (".py", ".ipynb", ".yaml", ".yml", ".r", ".jl", ".c", ".cc", ".cpp", ".h", ".hpp",
            ".m", ".sh", ".toml", ".cfg", ".ini", ".json")


def is_code_path(p: str) -> bool:
    """Files whose uncommitted changes matter for identifying the code."""
    if p.startswith(("log/", "report/")) or re.match(r"experiments/[^/]+/(output|output_quick|imported)/", p):
        return False
    return p.lower().endswith(CODE_EXT) or p.endswith("requirements.txt")


def git_state(root: Path = None):
    """(short commit hash, [code files with uncommitted changes])."""
    root = Path(root or ROOT)
    commit = git("rev-parse", "--short", "HEAD", cwd=root, check=False) or "none"
    return commit, [p for p in status_paths(root=root) if is_code_path(p)]


def code_field():
    commit, dirty = git_state()
    s = f"commit `{commit}`"
    if dirty:
        s += "; uncommitted changes in " + ", ".join(f"`{d}`" for d in dirty[:8])
        if len(dirty) > 8:
            s += f" and {len(dirty) - 8} more"
    return s, dirty


def need_git_name():
    name = git("config", "user.name", check=False)
    if not name:
        sys.exit('Git does not know your name yet. Run once:\n'
                 '    git config --global user.name  "Your Full Name"\n'
                 '    git config --global user.email "the e-mail of your GitHub account"')
    return name


def taken_names():
    """Entry file names already used here or in the group's repository on GitHub."""
    names = {p.name for p in LOG.glob("*.md")}
    if git("remote", check=False):
        try:
            subprocess.run(["git", "fetch", "-q"], cwd=ROOT, capture_output=True, timeout=30)
        except (subprocess.TimeoutExpired, OSError):
            pass
        up = git("rev-parse", "--abbrev-ref", "@{u}", check=False)
        if up:
            names |= {Path(x).name for x in
                      git("ls-tree", "--name-only", up, "log/", check=False).splitlines()}
    return names


def cmd_new(a):
    project = load_project()
    date = a.date or dt.date.today().isoformat()
    base = f"{date}_{slugify(a.title)}"
    taken = taken_names()
    name, k = f"{base}.md", 2
    while name in taken:
        name, k = f"{base}-{k}.md", k + 1
    path = LOG / name
    author = a.author or need_git_name()
    if not a.author and member_names(project) and author not in member_names(project):
        print(f"warning: your Git name '{author}' is not in the member list "
              f"({', '.join(member_names(project))}). Fix it with git config --global user.name.")
    if a.no_code:
        code, note = "n/a", "n/a"
    else:
        code, dirty = code_field()
        note = CODE_NOTE
        if dirty:
            print("note: the code has uncommitted changes; they are listed in the entry's Code "
                  "field.\n      To record a clean version, run  python tools/logtool.py save -m "
                  "\"...\"  and then create the entry.")
    path.write_text(TEMPLATE.format(title=a.title, date=date, author=author, code=code,
                                    code_note=note), encoding="utf-8")
    print(f"created {path.relative_to(ROOT).as_posix()}  <- edit this file, then run: "
          f"python tools/logtool.py save")
    cmd_index(a, quiet=True)


# ----------------------------------------------------------------- figures
IMG_LINK_RE = re.compile(r"(!\[[^\]]*\]\()([^)\s]+)(\))")
PROTECTED_RE = re.compile(r"(```.*?```|<!--.*?-->|`[^`\n]*`)", re.S)


def _outside_protected(text, fn):
    """Apply fn to the parts of text outside code blocks, inline code and comments."""
    parts = PROTECTED_RE.split(text)
    return "".join(p if i % 2 else fn(p) for i, p in enumerate(parts))


def figure_links(text):
    found = []
    _outside_protected(text, lambda s: found.extend(m.group(2) for m in IMG_LINK_RE.finditer(s)) or s)
    return found


def frozen_dir(entry_path: Path) -> Path:
    return entry_path.parent / "figs" / entry_path.stem


def outside_repo(target: str, entry_path: Path):
    if re.match(r"^[A-Za-z]:[\\/]|^[/\\~]", target):
        return True
    try:
        (entry_path.parent / target).resolve().relative_to(ROOT.resolve())
        return False
    except ValueError:
        return True


def _same(a: Path, b: Path) -> bool:
    return a.stat().st_size == b.stat().st_size and a.read_bytes() == b.read_bytes()


def freeze_figures(entry_path: Path):
    """Copy every embedded figure into log/figs/<entry>/ and point the links there.
    Returns (errors, copied files)."""
    errors, copied = [], []
    folder = frozen_dir(entry_path)

    def fix(m):
        target = m.group(2)
        if re.match(r"[a-z]+://", target):
            errors.append(f"figure from the web: {target} (save it into the repository first)")
            return m.group(0)
        if outside_repo(target, entry_path):
            errors.append(f"figure outside the repository: {target} "
                          "(copy it into the repository folder first)")
            return m.group(0)
        src = (entry_path.parent / target).resolve()
        if not src.is_file():
            errors.append(f"figure not found: {target}")
            return m.group(0)
        if src.parent == folder.resolve():
            return m.group(0)
        folder.mkdir(parents=True, exist_ok=True)
        dst, k = folder / src.name, 2
        while dst.exists() and not _same(dst, src):
            dst, k = folder / f"{src.stem}-{k}{src.suffix}", k + 1
        if not dst.exists():
            shutil.copy2(src, dst)
            copied.append(dst.relative_to(ROOT).as_posix())
        return m.group(1) + dst.relative_to(entry_path.parent).as_posix() + m.group(3)

    text = entry_path.read_text(encoding="utf-8")
    new = _outside_protected(text, lambda s: IMG_LINK_RE.sub(fix, s))
    if new != text and not errors:
        entry_path.write_text(new, encoding="utf-8")
    return errors, copied


def png_text(path: Path) -> dict:
    """Text chunks of a PNG file (where the experiment helper stores provenance)."""
    import zlib
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        return {}
    out, i = {}, 8
    while i + 8 <= len(data):
        n = int.from_bytes(data[i:i + 4], "big")
        typ, body = data[i + 4:i + 8], data[i + 8:i + 8 + n]
        if typ == b"tEXt":
            k, _, v = body.partition(b"\x00")
            out[k.decode("latin-1")] = v.decode("latin-1")
        elif typ == b"iTXt":
            k, _, rest = body.partition(b"\x00")
            comp, rest = rest[0], rest[2:]
            _, _, rest = rest.partition(b"\x00")
            _, _, txt = rest.partition(b"\x00")
            out[k.decode("utf-8")] = (zlib.decompress(txt) if comp else txt).decode("utf-8")
        elif typ == b"IEND":
            break
        i += 12 + n
    return out


def cmd_figinfo(a):
    """Provenance of the figures of an entry (or of given image files).
    An entry can be given by its file name or any part of it, e.g. 'antithetic'."""
    files = []
    for x in a.items:
        p = Path(x)
        cand = [p if p.is_absolute() else Path.cwd() / p, ROOT / p]
        image = next((c for c in cand if c.is_file() and c.suffix.lower() != ".md"), None)
        if image:
            files.append(image.resolve())
            continue
        stem = Path(x).name[:-3] if x.endswith(".md") else Path(x).name
        es = [e for e in entries()]
        hits = [e for e in es if e.path.stem == stem] or [e for e in es if stem in e.path.stem]
        if not hits:
            sys.exit(f"No entry or image file matches '{x}'. Entries:\n    " +
                     "\n    ".join(e.path.stem for e in es))
        if len(hits) > 1:
            sys.exit(f"'{x}' matches several entries; be more specific:\n    " +
                     "\n    ".join(e.path.stem for e in hits))
        e = hits[0]
        links = figure_links(e.text)
        print(f"{e.path.stem}: {len(links)} figure(s)")
        files += [(e.path.parent / t).resolve() for t in links]
    for f in files:
        try:
            rel = f.relative_to(ROOT.resolve()).as_posix()
        except ValueError:
            rel = f
        info = png_text(f) if f.exists() and f.suffix.lower() == ".png" else {}
        prov = info.get("Comment") or info.get("Description")
        if not f.exists():
            prov = "(file not found)"
        print(f"{rel}\n    " + (prov.replace("\n", "\n    ") if prov else
                                 "(no provenance recorded: this figure was not saved by the experiment "
                                 "helper's ex.save_figure)"))


# ----------------------------------------------------------------- experiment
def cmd_experiment(a):
    name = a.name
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        sys.exit("experiment names: lower case letters, digits and _, e.g. lsm_basis")
    src = ROOT / "experiments" / "_template"
    dst = ROOT / "experiments" / name
    if not src.exists():
        sys.exit("experiments/_template is missing")
    if dst.exists():
        sys.exit(f"experiments/{name} already exists")
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("output*", "__pycache__"))
    print(f"created experiments/{name}/run.py and experiments/{name}/configs/base.yaml\n"
          f"run it with:  python experiments/{name}/run.py base")


# ----------------------------------------------------------------- init
def remote_url():
    u = git("remote", "get-url", "origin", check=False)
    m = re.match(r"(?:git@github\.com:|https://github\.com/)([^/]+/[^/]+?)(?:\.git)?/?$", u)
    return f"https://github.com/{m.group(1)}" if m else u


def cmd_init(a):
    project = load_project()
    if project.get("initialised") and not a.force:
        sys.exit("This repository is already initialised (project.json).")
    gname = need_git_name()
    print("Initialising the project repository. Press Enter to accept a [default].\n")
    num = a.project if a.project is not None else ask("Project number (see the project list)")
    try:
        num = int(num)
    except (TypeError, ValueError):
        sys.exit("A project number is needed, e.g. 4.")
    title0, ref0 = PROJECTS.get(num, ("", ""))
    title = a.title or ask("Short project title", title0) or "TITLE"
    reference = a.reference or ask("Main reference", ref0) or "REFERENCE"
    group = a.group or ask("Group name, as allocated (e.g. G2)")
    group = re.sub(r"[^A-Za-z0-9_-]", "", group or "")
    if not group:
        sys.exit("A group name is needed.")
    members = []
    if a.member:
        for m in a.member:
            n, _, gh = m.partition(":")
            members.append({"name": n.strip(), "github": gh.strip()})
    else:
        print("\nGroup members: full name exactly as each member set it in "
              "`git config user.name`, and GitHub username. Empty name to finish.")
        while len(members) < 4:
            n = ask(f"  Member {len(members) + 1} full name", gname if not members else "")
            if not n:
                break
            members.append({"name": n, "github": ask(f"  {n}: GitHub username")})
    if not members:
        sys.exit("At least one member is needed.")
    url = remote_url()
    project.update({"initialised": True, "project": num, "title": title, "reference": reference,
                    "group": group, "members": members, "repo_url": url})
    subs = {
        "{{PROJECT}}": str(num), "{{TITLE}}": title, "{{GROUP}}": group,
        "{{REFERENCE}}": reference, "{{REPO_URL}}": url,
        "{{MEMBERS_TABLE}}": "\n".join(
            f"| {m['name']} | " + (f"[@{m['github']}](https://github.com/{m['github']})"
                                   if m["github"] else "") + " |" for m in members),
        "{{MEMBERS_TEX}}": ", ".join(tex_escape(m["name"]) for m in members),
        "{{MEMBERS_CONTRIB}}": "".join(f"{tex_escape(m['name'])} & \\dots \\\\\n" for m in members),
        "{{REFERENCE_TEX}}": tex_escape(reference),
    }
    for rel in ("README.md", "report/report.tex"):
        f = ROOT / rel
        if f.exists():
            t = f.read_text(encoding="utf-8")
            for k, v in subs.items():
                t = t.replace(k, v)
            f.write_text(t, encoding="utf-8")
    (ROOT / "project.json").write_text(json.dumps(project, indent=2, ensure_ascii=False) + "\n",
                                       encoding="utf-8")
    cmd_index(a, quiet=True)
    if gname not in member_names(project):
        print(f"\nwarning: your Git name '{gname}' is not one of the member names.")
    git("add", "-A")
    git("commit", "-q", "-m", f"Initialise project {num}, group {group}")
    print(f"\nInitialised project {num} ({title}), group {group}: "
          + ", ".join(member_names(project)))
    push()
    print("\nNext:\n  - the other members run `git pull` (or clone the repository now);"
          f"\n  - send the repository address to the instructor: {url}"
          "\n  - write the first entry: python tools/logtool.py new \"Reading notes and plan\" --no-code")


# ----------------------------------------------------------------- save
MAX_MB = 20


def push():
    has_upstream = subprocess.run(["git", "rev-parse", "--abbrev-ref", "@{u}"], cwd=ROOT,
                                  capture_output=True).returncode == 0
    if not git("remote", check=False):
        print("No remote repository configured: committed locally only.")
        return
    if has_upstream:
        r = subprocess.run(["git", "pull", "--no-rebase", "--no-edit", "-q"], cwd=ROOT,
                           capture_output=True, text=True)
        conflicts = git("diff", "--name-only", "--diff-filter=U", check=False).splitlines()
        if r.returncode != 0 and conflicts == ["log/README.md"]:
            # only the generated index conflicts: regenerate it and finish the merge
            cmd_index(quiet=True)
            git("add", "log/README.md")
            git("commit", "-q", "--no-edit")
            print("merged the others' changes (log index regenerated)")
        elif r.returncode != 0:
            sys.exit("Could not merge the others' changes automatically:\n" + r.stdout + r.stderr +
                     "\nOpen the files listed as CONFLICT, keep the right content, remove the "
                     "<<<<<<< ======= >>>>>>> lines, then run: python tools/logtool.py save")
        cmd = ["git", "push", "-q"]
    else:
        cmd = ["git", "push", "-q", "-u", "origin", "HEAD"]
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("Push failed:\n" + r.stderr)
    print("pushed to GitHub")


def pending_entries():
    """Entry files that are new or changed since the last commit."""
    out = []
    for p in status_paths("log"):
        if p.startswith("log/") and p.count("/") == 1 and p.endswith(".md") \
                and not p.endswith("README.md") and (ROOT / p).exists():
            out.append(ROOT / p)
    return out


def rename_clashing_entries():
    """A new (never committed) entry whose file name another member has meanwhile
    pushed is renamed to the next free name, with its frozen figures."""
    remote = set()
    if git("remote", check=False):
        try:
            subprocess.run(["git", "fetch", "-q"], cwd=ROOT, capture_output=True, timeout=30)
        except (subprocess.TimeoutExpired, OSError):
            return
        up = git("rev-parse", "--abbrev-ref", "@{u}", check=False)
        if up:
            remote = {Path(x).name for x in
                      git("ls-tree", "--name-only", up, "log/", check=False).splitlines()}
    for p in pending_entries():
        if p.name not in remote or git("ls-files", p.relative_to(ROOT).as_posix(), check=False):
            continue
        taken = remote | {q.name for q in LOG.glob("*.md")}
        base, k = re.sub(r"-\d+$", "", p.stem), 2
        while f"{base}-{k}.md" in taken:
            k += 1
        new = p.with_name(f"{base}-{k}.md")
        text = p.read_text(encoding="utf-8").replace(f"figs/{p.stem}/", f"figs/{new.stem}/")
        new.write_text(text, encoding="utf-8")
        p.unlink()
        if frozen_dir(p).exists():
            frozen_dir(p).rename(frozen_dir(new))
        print(f"renamed {p.name} -> {new.name} (another member used that name first)")


def cmd_save(a):
    need_git_name()
    rename_clashing_entries()
    if (ROOT / ".git" / "MERGE_HEAD").exists():
        left = git("diff", "--name-only", "--diff-filter=U", check=False).splitlines()
        left = [f for f in left if f != "log/README.md"]
        if left:
            sys.exit("A merge is in progress with unresolved conflicts in: " + ", ".join(left) +
                     "\nEdit these files (remove the <<<<<<< ======= >>>>>>> markers), then save again.")
    project = load_project()
    held = []
    for p in pending_entries():
        errs, copied = freeze_figures(p)
        for c in copied:
            print(f"froze {c}")
        e = Entry(p)
        cerrs, warns = check_entry(e, project, pending=True, figures=False)
        for m in errs + cerrs:
            print(f"ERROR   {p.name}: {m}")
        for m in warns:
            print(f"warning {p.name}: {m}")
        if errs or cerrs:
            held.append(p)
    held_names = {p.name for p in held}
    cmd_index(quiet=True, exclude=held_names)          # index of what is committed
    git("add", "-A")
    for p in held:                                      # unfinished entries stay out
        git("reset", "-q", "--", p.relative_to(ROOT).as_posix(), check=False)
        fd = frozen_dir(p)
        if fd.exists():
            git("reset", "-q", "--", fd.relative_to(ROOT).as_posix(), check=False)
    for p in pending_entries():                         # frozen figures always go with their entry
        fd = frozen_dir(p)
        if p.name not in held_names and fd.exists():
            git("add", "-f", "--", fd.relative_to(ROOT).as_posix())
    staged = git("diff", "--cached", "--name-only").splitlines()
    big = [f for f in staged if (ROOT / f).is_file()
           and (ROOT / f).stat().st_size > MAX_MB * 2**20]
    if big:
        git("reset", "-q", "--", *big)
        print(f"not committed (larger than {MAX_MB} MB; add them to .gitignore): {', '.join(big)}")
        staged = [f for f in staged if f not in big]
    if held:
        print("held back (not committed until fixed): " + ", ".join(p.name for p in held))
    if staged:
        titles = [Entry(ROOT / f).title for f in staged
                  if f.startswith("log/") and f.count("/") == 1 and ENTRY_RE.match(Path(f).name)
                  and (ROOT / f).exists()]
        msg = a.message or ("Log: " + "; ".join(titles) if titles else "Update " +
                            ", ".join(sorted({f.split('/')[0] for f in staged})))
        git("commit", "-q", "-m", msg)
        print(f"committed {len(staged)} file(s): {msg}")
    else:
        print("nothing to commit")
    cmd_index(quiet=True)                               # local index again lists everything
    push()
    if held:
        sys.exit(1)


# ----------------------------------------------------------------- reproduce
def reproduce_rows():
    f = ROOT / "REPRODUCE.md"
    if not f.exists():
        sys.exit("REPRODUCE.md not found")
    rows = []
    for line in f.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2 or not line.lstrip().startswith("|"):
            continue
        m = re.search(r"`([^`]+)`", cells[1])
        if not m or "<" in m.group(1):
            continue
        rows.append((cells[0], m.group(1)))
    return rows


def cmd_reproduce(a):
    rows = reproduce_rows()
    if not rows:
        sys.exit("REPRODUCE.md has no table rows with a command in `backticks`.")
    if a.list:
        for item, c in rows:
            print(f"{item:30s} {c}")
        return
    if a.items:
        rows = [r for r in rows if any(x.lower() in r[0].lower() for x in a.items)]
        if not rows:
            sys.exit("no matching item; see --list")
    done = []
    for item, c in rows:
        args = shlex.split(c)
        if args and args[0] in ("python", "python3", "py"):
            args[0] = sys.executable
        if a.quick:
            args.append("--quick")
        print(f"\n=== {item}: {c}{' --quick' if a.quick else ''}")
        t0 = time.time()
        rc = subprocess.run(args, cwd=ROOT).returncode
        done.append((item, rc, time.time() - t0))
        if rc != 0 and not a.keep_going:
            break
    print("\n| Item | Result | Seconds |\n|---|---|---:|")
    for item, rc, sec in done:
        print(f"| {item} | {'ok' if rc == 0 else 'FAILED'} | {sec:.0f} |")
    if any(rc for _, rc, _ in done) or len(done) < len(rows):
        sys.exit(1)


# ----------------------------------------------------------------- index
def cmd_index(a=None, quiet=False, exclude=()):
    es = [e for e in entries() if e.name not in exclude]
    project = load_project()
    lines = [INDEX_START, "", f"{len(es)} entries, newest first.", "",
             "| Date | Entry | Author(s) |", "|---|---|---|"]
    for e in reversed(es):
        lines.append(f"| {e.date} | [{e.title or e.name}]({e.name}) | {', '.join(e.authors)} |")
    counts = defaultdict(int)
    for e in es:
        for au in e.authors:
            counts[au] += 1
    names = member_names(project) or sorted(counts)
    if names:
        lines += ["", "Entries per member: " +
                  ", ".join(f"{n} {counts.get(n, 0)}" for n in names)]
    lines += ["", INDEX_END]
    idx = LOG / "README.md"
    head = "# Development log\n\nSee [LOG_GUIDE.md](../LOG_GUIDE.md) for the rules.\n\n"
    if idx.exists():
        old = idx.read_text(encoding="utf-8")
        if INDEX_START in old:
            head = old.split(INDEX_START)[0]
    idx.write_text(head + "\n".join(lines) + "\n", encoding="utf-8")
    if not quiet:
        print(f"updated log/README.md ({len(es)} entries)")


# ----------------------------------------------------------------- check
def maths_problems(text):
    """Inline formulas $...$ that pandoc (PDF export) and GitHub do not recognise."""
    out = []
    body = re.sub(r"```.*?```|<!--.*?-->", lambda m: " " * len(m.group(0)), text, flags=re.S)
    body = re.sub(r"\$`[^`\n]*`\$", lambda m: " " * len(m.group(0)), body)    # GitHub's $`...`$
    body = re.sub(r"`[^`\n]*`", lambda m: " " * len(m.group(0)), body)
    body = re.sub(r"\$\$.*?\$\$", lambda m: re.sub(r"[^\n]", " ", m.group(0)), body, flags=re.S)
    for para in re.split(r"\n\s*\n", body):
        pos = [m.start() for m in re.finditer(r"(?<!\\)\$", para)]
        for a, b in zip(pos[0::2], pos[1::2]):
            f = para[a:b + 1]
            short = " ".join(f.split())[:40]
            if "\n" in f:
                out.append(f"formula {short} is broken over two lines: keep $...$ on one line")
            elif f[1:2].isspace():
                out.append(f"formula {short}: no space directly after the opening $")
            elif f[-2:-1].isspace():
                out.append(f"formula {short}: no space directly before the closing $")
            elif para[b + 1:b + 2].isdigit():
                out.append(f"formula {short}: a digit directly after the closing $ "
                           "(add a space, or put the digit inside the formula)")
        if len(pos) % 2:
            tail = " ".join(para[pos[-1]:pos[-1] + 30].split())
            out.append(f"unmatched $ near '{tail}' (write \\$ for a dollar sign)")
    return out


def check_entry(e: Entry, project: dict, pending=False, figures=True):
    """pending: entry not yet committed (save will freeze its figures);
    figures=False: skip figure links (save has already reported them)."""
    errors, warnings = [], []
    if not ENTRY_RE.match(e.name):
        errors.append("file name must be YYYY-MM-DD_short-title.md (lower case, hyphens)")
    if not e.title:
        errors.append("missing title line '# ...'")
    for f in REQUIRED_FIELDS:
        if not e.fields.get(f):
            errors.append(f"missing field '- **{f}:** ...'")
    d = e.fields.get("Date", "")
    if d:
        try:
            dt.date.fromisoformat(d)
        except ValueError:
            errors.append(f"Date '{d}' is not YYYY-MM-DD")
        if e.file_date and d != e.file_date:
            errors.append(f"Date field {d} differs from file name date {e.file_date}")
    code = e.fields.get("Code", "")
    no_code = code.lower() in NO_CODE
    if code and not no_code:
        m = re.search(r"`?([0-9a-f]{7,40})`?", code)
        if not m:
            warnings.append("Code field has no commit hash")
        elif (ROOT / ".git").exists() and subprocess.run(
                ["git", "cat-file", "-e", m.group(1) + "^{commit}"], cwd=ROOT,
                capture_output=True).returncode != 0:
            warnings.append(f"commit {m.group(1)} not found in this repository")
        if "uncommitted" in code:
            warnings.append("the code had uncommitted changes: say in 'Code and runs' what differed")
    names = member_names(project)
    for au in e.authors:
        if names and au not in names:
            warnings.append(f"author '{au}' is not a member listed in project.json")
    for s in REQUIRED_SECTIONS:
        if s not in e.sections:
            errors.append(f"missing section '## {s}'")
        elif not e.section_text(s):
            errors.append(f"section '## {s}' is empty")
    for s in e.sections:
        if s not in REQUIRED_SECTIONS + OPTIONAL_SECTIONS:
            warnings.append(f"unexpected section '## {s}' (use ### for subsections)")
    if "AI assistance" in e.sections and not e.section_text("AI assistance"):
        warnings.append("empty '## AI assistance' section: fill it in or delete it")
    res = "\n".join(e.sections.get("Results", []))
    if not no_code and not re.search(r"\|\s*-{3,}|!\[|```|\.pdf\)", res):
        warnings.append("Results contain no table, figure or program output")
    body = re.sub(r"```.*?```|<!--.*?-->", "", e.text, flags=re.S)
    body = re.sub(r"`[^`\n]*`", "", body)
    if body.count("$$") % 2:
        errors.append("unbalanced $$ (display maths)")
    for m in maths_problems(e.text):
        warnings.append(m + " -- it will show as raw text on GitHub and break the PDF export")
    frozen = frozen_dir(e.path).resolve()
    for target in (figure_links(e.text) if figures else []):
        if re.match(r"[a-z]+://", target) or outside_repo(target, e.path):
            errors.append(f"figure outside the repository: {target}")
            continue
        src = (e.path.parent / target).resolve()
        if not src.exists():
            errors.append(f"figure not found: {target}")
        elif src.parent != frozen:
            msg = f"figure {target} is not in the entry's folder log/figs/{e.path.stem}/"
            if pending:
                pass                                   # save freezes it before checking
            else:
                errors.append(msg + " (run: python tools/logtool.py save)")
    for target in LINK_RE.findall(body):
        if re.match(r"[a-z]+://|#|mailto:", target):
            continue
        if not (e.path.parent / target.split("#")[0]).exists():
            errors.append(f"linked file not found: {target}")
    return errors, warnings


def run_checks(verbose=True) -> int:
    project = load_project()
    es = entries()
    pend = {p.name for p in pending_entries()} if (ROOT / ".git").exists() else set()
    n_err = 0
    for e in es:
        errs, warns = check_entry(e, project, pending=e.name in pend)
        if verbose:
            for m in errs:
                print(f"ERROR   {e.name}: {m}")
            for m in warns:
                print(f"warning {e.name}: {m}")
        n_err += len(errs)
    if verbose:
        for p in LOG.glob("*"):
            if p.is_file() and p.suffix != ".md":
                print(f"warning log/{p.name}: put figures in log/figs/ and derivations in log/derivations/")
        print(f"{len(es)} entries checked, {n_err} error(s)")
    return n_err


def cmd_check(a):
    sys.exit(1 if run_checks() else 0)


# ----------------------------------------------------------------- git info
def first_commit(relpath: str, ref: str = "HEAD"):
    """(ISO date, author name) of the commit that added a file, or None."""
    out = git("log", ref, "--diff-filter=A", "--format=%aI|%an", "--", relpath, check=False)
    if not out:
        return None
    d, n = out.splitlines()[-1].split("|", 1)
    return d[:10], n


def n_edits(relpath: str, ref: str = "HEAD") -> int:
    out = git("log", ref, "--format=%H", "--", relpath, check=False)
    return max(0, len(out.splitlines()) - 1)


# ----------------------------------------------------------------- export
def materialise(ref):
    """Return (tmpdir, root) with the repository content at `ref`."""
    tmp = Path(tempfile.mkdtemp(prefix="logexport-"))
    if ref:
        data = subprocess.run(["git", "archive", ref, "log", "project.json"], cwd=ROOT,
                              capture_output=True, check=True).stdout
        with tarfile.open(fileobj=io.BytesIO(data)) as tf:
            tf.extractall(tmp)
        return tmp, tmp
    return tmp, ROOT


def pdf_tweaks(text):
    """Line-breakable file paths in the header fields; symbols missing from text fonts."""
    out = []
    for line in text.split("\n"):
        if FIELD_RE.match(line):
            line = re.sub(r"`([^`{}\\]+)`", r"\\path{\1}", line)
        out.append(line)
    text = "\n".join(out)
    parts = re.split(r"(\$\$.*?\$\$|\$[^$\n]+\$|```.*?```|`[^`\n]*`)", text, flags=re.S)
    for i in range(0, len(parts), 2):          # outside maths and code only
        parts[i] = parts[i].replace("≈", "\\ensuremath{\\approx}").replace("±", "\\ensuremath{\\pm}")
    for i in range(1, len(parts), 2):          # file paths in inline code: allow line breaks
        m = re.fullmatch(r"`([^`{}\\\s]*/[^`{}\\\s]*)`", parts[i])
        if m:
            parts[i] = f"\\path{{{m.group(1)}}}"
    return "".join(parts)


def latex_error(output):
    """The '! ...' error message and the 'l.<n>' line from LaTeX output: (message, n or None)."""
    lines = output.splitlines()
    i = next((k for k, ln in enumerate(lines) if ln.startswith("!")), None)
    if i is None:
        return "\n".join(lines[-15:]), None
    msg = []
    for ln in lines[i:i + 20]:
        msg.append(ln)
        m = re.match(r"l\.(\d+)", ln)
        if m:
            return "\n".join(msg), int(m.group(1))
    return "\n".join(msg[:3]), None


def locate_failure(tex_file, line_no, es):
    """Name the entry containing line line_no of the exported .tex file."""
    lines = tex_file.read_text(encoding="utf-8").splitlines()
    if not line_no or line_no > len(lines):
        return ""
    entry = next((ln.split()[-1] for ln in reversed(lines[:line_no]) if "LOGTOOL-ENTRY" in ln), None)
    if not entry:
        return ""
    msg = f"\nThe problem is in log/{entry}, near:\n    {lines[line_no - 1].strip()[:100]}\n"
    e = next((x for x in es if x.name == entry), None)
    hints = maths_problems(e.text) if e else []
    if hints:
        msg += "Likely cause:\n    " + "\n    ".join(hints) + "\n"
    return msg + "Fix the entry (see the student manual, 'Maths, tables and figures') and export again."


def copy_images(md, logdir, texdir):
    """Copy the images embedded in md into texdir, so that the .tex file compiles on its own.
    Images inside log/ keep their relative path (figs/<entry>/...); others go to media/."""
    def fix(m):
        link = m.group(2)
        if re.match(r"[a-zA-Z]+://", link):
            return m.group(0)
        src = (logdir / link).resolve()
        if not src.is_file():
            return m.group(0)
        try:
            rel = src.relative_to(logdir.resolve()).as_posix()
        except ValueError:
            rel = f"media/{src.name}"
        dest = texdir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        return m.group(1) + rel + m.group(3)
    return _outside_protected(md, lambda s: IMG_LINK_RE.sub(fix, s))


def shown(p):
    """Path relative to the current folder if possible (for messages)."""
    try:
        return p.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return str(p)


def build_pdf(md, logdir, out, es):
    """Write the LaTeX source <out>_tex/<out>.tex (with the figures it needs), compile it to out."""
    eng = next((x for x in ("xelatex", "lualatex", "pdflatex") if shutil.which(x)), None)
    if not eng:
        sys.exit("no LaTeX engine found: use --format html instead")
    texdir = out.parent / f"{out.stem}_tex"
    if texdir.exists():
        shutil.rmtree(texdir)
    texdir.mkdir(parents=True)
    src = texdir / "combined.md"
    src.write_text(copy_images(md, logdir, texdir), encoding="utf-8")
    tex = texdir / f"{out.stem}.tex"
    opts = ["-s", "--toc", "--toc-depth=1", "-f", "markdown-implicit_figures",
            "-V", "geometry:margin=2.2cm", "-V", "header-includes=\\usepackage{xurl}",
            "-V", "colorlinks=true", "-V", "fontsize=11pt"]

    def compile_(extra):
        r = subprocess.run(["pandoc", src.name, "-o", tex.name] + opts + extra,
                           cwd=texdir, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("pandoc failed:\n" + r.stderr)
        for _ in range(3):      # LaTeX needs repeated runs for the table of contents
            r = subprocess.run([eng, "-interaction=nonstopmode", "-halt-on-error", tex.name],
                               cwd=texdir, capture_output=True, text=True, errors="replace")
            if r.returncode != 0 or not re.search(r"Rerun to get|Label\(s\) may have changed", r.stdout):
                return r
        return r

    r = compile_([])
    if r.returncode != 0 and "lmodern.sty" in r.stdout and eng != "pdflatex":
        # TeX installation without the lmodern package: use the OpenType fonts
        r = compile_(["-V", "fontfamily=fontspec", "-V", "mainfont=Latin Modern Roman",
                      "-V", "mathfont=Latin Modern Math"])
    src.unlink()
    where = shown(texdir)
    if r.returncode != 0:
        err, line_no = latex_error(r.stdout)
        sys.exit(f"LaTeX ({eng}) failed on {where}/{tex.name}:\n{err}\n"
                 + locate_failure(tex, line_no, es)
                 + f"\n(Full LaTeX log: {where}/{tex.stem}.log)")
    shutil.move(str(texdir / f"{out.stem}.pdf"), str(out))
    for ext in (".aux", ".log", ".out", ".toc"):
        p = texdir / f"{tex.stem}{ext}"
        if p.exists():
            p.unlink()
    print(f"wrote {where}/{tex.name}  (LaTeX source with its figures; "
          f"to rebuild the PDF there: {eng} {tex.name}, run twice)")


def cmd_export(a):
    tmp, root = materialise(a.ref)
    try:
        project = load_project(root)
        es = entries(root / "log", a.ref or "HEAD")
        use_git = (ROOT / ".git").exists()
        title = f"Development log: Project {project.get('project', '?')}"
        if project.get("title"):
            title += f": {project['title']}"
        sub = f"Group {project.get('group', '?')}: " + ", ".join(member_names(project))
        snap = a.ref or "working tree"
        if use_git:
            try:
                snap += f" @ {git('rev-parse', '--short', a.ref or 'HEAD')}"
            except Exception:
                pass
        parts = [f"---\ntitle: \"{title}\"\nsubtitle: \"{sub}\"\n"
                 f"date: \"Snapshot: {snap}, exported {dt.date.today().isoformat()}\"\n---\n"]
        for e in es:
            text = e.text
            if use_git:
                fc = first_commit(f"log/{e.name}", a.ref or "HEAD")
                if fc:
                    note = f"*First committed {fc[0]} by {fc[1]}"
                    k = n_edits(f"log/{e.name}", a.ref or "HEAD")
                    note += f"; edited in {k} later commit(s).*" if k else ".*"
                    text = re.sub(r"^(# .*\n)", r"\1\n" + note + "\n", text, count=1)
            text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
            text = re.sub(r"\$`(.+?)`\$", r"$\1$", text)   # GitHub-only $`...`$ syntax
            if a.format == "pdf":
                text = pdf_tweaks(text)
                # invisible marker, used to name the entry if LaTeX fails
                text = f"```{{=latex}}\n% LOGTOOL-ENTRY {e.name}\n```\n\n" + text
            parts.append(text.strip() + "\n\n\\newpage\n" if a.format == "pdf" else text.strip() + "\n\n---\n")
        md = "\n\n".join(parts)
        logdir = root / "log"
        out = Path(a.output or f"log_{(a.ref or 'current').replace('/', '_')}.{a.format}").resolve()
        if a.format == "md":
            out.write_text(md, encoding="utf-8")
        elif not shutil.which("pandoc"):
            sys.exit("pandoc not found: install it from https://pandoc.org or use --format md")
        elif a.format == "pdf":
            build_pdf(md, logdir, out, es)
        else:
            src = tmp / "combined.md"
            src.write_text(md, encoding="utf-8")
            r = subprocess.run(["pandoc", str(src), "-o", str(out), "--toc", "--toc-depth=1",
                                f"--resource-path={logdir}", "-f", "markdown-implicit_figures",
                                "--standalone", "--embed-resources", "--mathml",
                                "--metadata", "title=" + title],
                               cwd=logdir, capture_output=True, text=True)
            if r.returncode != 0:
                sys.exit("pandoc failed:\n" + r.stderr)
        print(f"wrote {shown(out)}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# ----------------------------------------------------------------- stats
def iso_week(d: str) -> str:
    y, w, _ = dt.date.fromisoformat(d).isocalendar()
    return f"{y}-W{w:02d}"


def cmd_stats(a):
    """Overview for the instructor: regularity, authorship, late edits."""
    ref = a.ref or "HEAD"
    tmp, root = materialise(a.ref)
    try:
        project = load_project(root)
        es = entries(root / "log")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    names = member_names(project)
    tags = [t for t in git("tag", "--list", check=False).splitlines() if t]
    print(f"# Log statistics: Project {project.get('project', '?')}, group {project.get('group', '?')} ({ref})\n")
    print(f"{len(es)} entries.\n")

    print("## Entries\n")
    print("| Date | Entry | Author(s) | First commit | Committer | Late? | Edits |")
    print("|---|---|---|---|---|---|---|")
    for e in es:
        fc = first_commit(f"log/{e.name}", ref)
        late = ""
        if fc and e.date:
            lag = (dt.date.fromisoformat(fc[0]) - dt.date.fromisoformat(e.date)).days
            late = f"+{lag} d" if lag > 7 else ""
        print(f"| {e.date} | {e.title[:45]} | {', '.join(e.authors)} | "
              f"{fc[0] if fc else 'uncommitted'} | {fc[1] if fc else ''} | {late} | "
              f"{n_edits(f'log/{e.name}', ref)} |")
    print("\n'Late?' = committed more than 7 days after the entry date. "
          "'Edits' = later commits that changed the entry.\n")

    print("## Entries per member and month\n")
    months = sorted({e.date[:7] for e in es if e.date})
    who = names or sorted({au for e in es for au in e.authors})
    print("| Member | " + " | ".join(months) + " | Total |")
    print("|---|" + "---|" * (len(months) + 1))
    for n in who:
        row = [sum(1 for e in es if e.date.startswith(m) and n in e.authors) for m in months]
        print(f"| {n} | " + " | ".join(map(str, row)) + f" | {sum(row)} |")

    print("\n## Weekly activity (entries per ISO week)\n")
    if es:
        start = dt.date.fromisoformat(es[0].date)
        end = dt.date.fromisoformat(es[-1].date)
        per = defaultdict(int)
        for e in es:
            per[iso_week(e.date)] += 1
        d = start - dt.timedelta(days=start.weekday())
        while d <= end:
            w = iso_week(d.isoformat())
            print(f"    {w} ({d.isoformat()})  {'#' * per[w] or '.  <- no entry'}")
            d += dt.timedelta(days=7)

    print("\n## Frozen figures changed after they were first committed\n")
    changed = []
    for f in git("ls-tree", "-r", "--name-only", ref, "log/figs/", check=False).splitlines():
        if f.count("/") >= 3 and n_edits(f, ref) > 0:
            changed.append(f)
    print("- " + ("\n- ".join(changed) if changed else "none"))

    snap = [t for t in ("p1", "p2", "final") if t in tags]
    if snap:
        print("\n## Entries changed after a snapshot tag\n")
        for t in snap:
            changed = git("diff", "--name-only", "--diff-filter=MD", t, ref, "--", "log/*.md",
                          check=False).splitlines()
            changed = [c for c in changed if not c.endswith("README.md")]
            print(f"- after `{t}`: " + (", ".join(changed) if changed else "none"))


# ----------------------------------------------------------------- main
def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sp = p.add_subparsers(dest="cmd", required=True)
    i = sp.add_parser("init", help="fill in project, group and members (once)")
    i.add_argument("--project", type=int)
    i.add_argument("--group")
    i.add_argument("--member", action="append", metavar="'Name:github'")
    i.add_argument("--title")
    i.add_argument("--reference")
    i.add_argument("--force", action="store_true")
    i.set_defaults(func=cmd_init)
    n = sp.add_parser("new", help="create a new log entry")
    n.add_argument("title")
    n.add_argument("--author", help="e.g. \"Anna Nowak, Maria Wojcik\" for a joint entry")
    n.add_argument("--date", help="YYYY-MM-DD (default: today)")
    n.add_argument("--no-code", dest="no_code", action="store_true",
                   help="entry without computations (reading notes, derivation, plan)")
    n.set_defaults(func=cmd_new)
    x = sp.add_parser("experiment", help="create experiments/NAME from the template")
    x.add_argument("name")
    x.set_defaults(func=cmd_experiment)
    f = sp.add_parser("figinfo", help="provenance of the figures of an entry")
    f.add_argument("items", nargs="+", help="entry (file name or part of it, e.g. antithetic) or image files")
    f.set_defaults(func=cmd_figinfo)
    v = sp.add_parser("save", help="freeze figures, check, commit everything and push")
    v.add_argument("-m", "--message", help="commit message (default: from the entry titles)")
    v.set_defaults(func=cmd_save)
    r = sp.add_parser("reproduce", help="run the commands listed in REPRODUCE.md")
    r.add_argument("items", nargs="*", help="only items whose name contains these words")
    r.add_argument("--list", action="store_true", help="list the items and commands")
    r.add_argument("--quick", action="store_true", help="pass --quick to every command")
    r.add_argument("--keep-going", action="store_true", help="continue after a failure")
    r.set_defaults(func=cmd_reproduce)
    sp.add_parser("index", help="rebuild log/README.md").set_defaults(func=cmd_index)
    sp.add_parser("check", help="check the format of all entries").set_defaults(func=cmd_check)
    x = sp.add_parser("export", help="export the whole log as one PDF/HTML/Markdown file")
    x.add_argument("--ref", help="git tag or commit (e.g. p1); default: working tree")
    x.add_argument("--format", choices=["pdf", "html", "md"], default="pdf")
    x.add_argument("-o", "--output")
    x.set_defaults(func=cmd_export)
    s = sp.add_parser("stats", help="regularity and authorship overview (for the instructor)")
    s.add_argument("--ref", help="git tag or commit; default HEAD")
    s.set_defaults(func=cmd_stats)
    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
